/**
 * FormationRouter action types
 */
export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';
export const LOCATION_CHANGE_SIDE_EFFECT = '@@formation-router/LOCATION_CHANGE_SIDE_EFFECT';
export const LOCATION_CHANGE_SIDE_EFFECTS_COMPLETED = '@@formation-router/LOCATION_CHANGE_SIDE_EFFECTS_COMPLETED';
export const SET_ROUTE_UNMOUNT_SIDE_EFFECT_COUNT = '@@formation-router/SET_ROUTE_UNMOUNT_SIDE_EFFECT_COUNT';
export const ROUTE_UNMOUNT_SIDE_EFFECT_COMPLETED = '@@formation-router/ROUTE_UNMOUNT_SIDE_EFFECT_COMPLETED';
export const ALL_ROUTE_UNMOUNT_SIDE_EFFECTS_COMPLETED = '@@formation-router/ALL_ROUTE_UNMOUNT_SIDE_EFFECTS_COMPLETED';
export const ABANDON_ALL_ROUTE_UNMOUNT_SIDE_EFFECTS = '@@formation-router/ABANDON_ALL_ROUTE_UNMOUNT_SIDE_EFFECTS';
export const UNREGISTER_ROUTE_UNMOUNT_EFFECT = '@@formation-router/UNREGISTER_ROUTE_UNMOUNT_EFFECT';
